### ISSUE TITLE
Change Coverart is not working

### ISSUE THREAD

**Issue by qyen** [tesshucom/jpsonic#1051]
## Problem description

Change CoverArt action raise javascript error on chrome developer tool.
`Uncaught TypeError: coverArtService.setCoverArtImage is not a function`

`setCoverArtImage' may be 'saveCoverArtImage'.

version : Jpsonic 110.0.0-RELEASE

### Steps to reproduce

1. Open Album page
2. Click "Change CoverArt"(in japanese カバーアートの変更)button
3. Click image from Last.fm

**Comment by tesshucom** [comment]
Thank you for your report.

The following seems to be the cause.
fcd203b PMD(urgent) : LinguisticNaming
