### ISSUE TITLE
 Update to Lucene 7.7.1

### ISSUE THREAD

**Issue by tesshucom** [tesshucom/jpsonic#121]
Evaluation service of the library called [libraries.io](https://libraries.io/github/tesshucom/jpsonic) exists.
One point of evaluation is [Sourcerank,](https://libraries.io/github/tesshucom/jpsonic/sourcerank) in which there is a section called Outdated dependencies.

[The method of calculating SourceRank](https://github.com/librariesio/libraries.io/issues/1916) is currently being improved.
Judgment as to whether to fully trust is suspended.
However, information can be referred to.

**Comment by tesshucom** [comment]
Currently two libraries are subject to fatal alert.
 - javax.servlet:javax.servlet-api
- org.eclipse.persistence:org.eclipse.persistence.moxy 

Looks like an overcheck.
Since there are signs of upgrading to Spring 2. x on Airsonic, observe the course.

**Comment by tesshucom** [comment]
When comparing Airsonic and Jpsonic, there are two big differences.
 - Add icu4j
 - Lucene version is very different

Since icu 4 j is used in limited areas, it can be removed in the long term.
(I will not start it immediately.Character string conversion specific to Japanese.)

Lucene has adopted 7.4, but now the latest is 7.6.
As changes include bug fixes and performance improvements, we check whether Lucene version upgrade and data migration are possible.

**Comment by tesshucom** [comment]
Add unit tests before migration.
 - Based on analysis specification of airsonic's current situation
 - As for alphabetic characters, Jpsonic should perform similar analysis

**Comment by tesshucom** [comment]
The test case was created for use with Airsonic's Analizer.
Fix it so that it can work with Jpsonic's Analizer.

**Comment by tesshucom** [comment]
- Add English stopword

as a result
 - The behavior related to UAX#29 changes.
 - Because it corresponded to Japanese, test case related to Japanese changed.
 - Other than that, it does not change.

**Comment by jp-searching** [comment]
In 7.4 to 7.7.1, there was no effect on the specification API grammar.
