### ISSUE TITLE
Specification change of stopward

### ISSUE THREAD

**Issue by tesshucom** [tesshucom/jpsonic#151]
In Subsonic and Airsonic traditionally English Stopward is used during analysis.

Jpsonic intentionally eliminates Stopward.
(It is often done in a system that emphasizes phrase search)

Add only "articles" in Stopward.
The reason is that the specification is easy for users to accept, less confusion and less waste.

It is obvious as a server specification that an article is removed when creating an index because it exists on the setting screen.
Even if the same thing is done at the time of searching, it is hard to feel uncomfortable in case of article in comparison with other stopward.

**Comment by tesshucom** [comment]
Filter queries as well as index.

**Comment by tesshucom** [comment]
The stopward resolved in these issues focuses on English.
A later fix will integrate English and Japanese stopwords and add unit tests.

**Comment by jp-searching** [comment]
Resolved as a filter implementation in AnalyzerFactory that is newly created in # 161.
