### ISSUE TITLE
 Delete Lock operation

### ISSUE THREAD

**Issue by tesshucom** [tesshucom/jpsonic#160]
* SearchService

Legacy server (lucene 3.0) had forced purge of lock file.

This method does not work because lucene currently adopted has different locking mechanism implementation.
When the actual lock is released, the lock is released from the file in the index directory, but the file lasts forever.
Since it is a non-atomic management file, it is better not to touch it.
(Currently it is meaningful as a write check to disk. If access to an unauthorized thread or inappropriate NAS occurs, you will get a more generic general error message.)

Jpsonic deletes the lock related process. Locks are not managed at the service level.
(It is equivalent to DB lock file management method)
If an accidental deadlock occurs, the framework outputs a message.

**Comment by jp-searching** [comment]
It is deleted simultaneously when dividing the function of SearchService in #161.
