### ISSUE TITLE
Unable to search MusicFolder

### ISSUE THREAD

**Issue by tesshucom** [tesshucom/jpsonic#165]
## Problem description
MusicFolder specification may malfunction depending on the name of MusicFolder.

### Steps to reproduce
 - Specify a directory name not divided by ClassicTokenizer but divided by UAX#29 in MusicFolder.

## Additional notes
 - Implementation method for issuing a multi query are slightly different from lucene 3.x and 7.x. Need proper field type and parser. There is a defect in this point.
 - If there is a defect in the parser, there is cases where a problem occurs in 7.x.
 - There is no test case that can cover these.

**Comment by tesshucom** [comment]
There seems to be a mix of meaningless queries, but there is no problem.

**Comment by jp-searching** [comment]
Added tests for SearchService (with almost the same granularity as other tests).
