### ISSUE TITLE
can not specify year

### ISSUE THREAD

**Issue by tesshucom** [tesshucom/jpsonic#166]
## Problem description

Search by year is not available.

### Steps to reproduce

Include Year in the search criteria.

## Additional notes
The new version of lucene does not allow you to specify a range null.
When replacing legacy code, it was not corrected to use with MAX or MIN of int.
This issue is also closed when #161 is closed because it has already been addressed in #161.

**Comment by jp-searching** [comment]
https://github.com/jp-searching/jpsonic/commit/4e70b4f2d52e6ca448c3509a4fc2ea67b64e72d5
