### ISSUE TITLE
[Jpsonic 111.5.0] Postgresql grammar exception for on every insert having a time stamp. 

### ISSUE THREAD

**Issue by masterblaster79** [tesshucom/jpsonic#1935]
Hi.

## Problem description

*Every DB INSERT where a timestamp is involved (add user/change password/add or modify media folder..) results in an sql exception like this:*

`org.springframework.jdbc.BadSqlGrammarException: PreparedStatementCallback; bad SQL grammar [update music_folder set path=?, name=?, enabled=?, changed=? where id=?]; nested exception is org.postgresql.util.PSQLException: Can't infer the SQL type to use for an instance of java.time.Instant. Use setObject() with an explicit Types value to specify the type to use.`

### Steps to reproduce

**

1. Fresh install of jpsonic war in tomcat container connecting to postgresql using jndi
2. Try to create a media folder

## System information

 * **Jpsonic version**: Jpsonic 111.5.0 – 2022-09-18
 * **Operating system**: *Ubuntu 22.04.1 LTS inside an Proxmox LXC container using kernel 5.19.17-1-pve*
 * **Java version**: openjdk version "11.0.17" 2022-10-18
OpenJDK Runtime Environment (build 11.0.17+8-post-Ubuntu-1ubuntu222.04)
OpenJDK 64-Bit Server VM (build 11.0.17+8-post-Ubuntu-1ubuntu222.04, mixed mode)*
 * **Proxy server**:  None
 * **Client**: *Firefox 107*
 * **Language**: *German*
 * **Tomcat/standalone**: *Tomcat*

## Additional notes
Tomcat context.xml:
```
<?xml version="1.0" encoding="UTF-8"?>
<Context>

    <WatchedResource>WEB-INF/web.xml</WatchedResource>
    <WatchedResource>WEB-INF/tomcat-web.xml</WatchedResource>
    <WatchedResource>${catalina.base}/conf/web.xml</WatchedResource>

    <Resource name="jdbc/jpsonicDB" auth="Container"
    type="javax.sql.DataSource"
    maxActive="20"
    maxIdle="30"
    maxWait="10000"
    username="jpsonic"
    password="XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
    driverClassName="org.postgresql.Driver"
    url='jdbc:postgresql://postgres/jpsonic?sessionVariables=stringtype=unspecified'/>
</Context>
```

DB related entries in jpsonic.properties:
```
DatabaseConfigType=jndi
DatabaseConfigJNDIName=jdbc/jpsonicDB
DatabaseUsertableQuote="
spring.datasource.jndi-name=jdbc/jpsonicDB

```

Postgresql version (external host):
```
ii  postgresql-13  13.8-0+deb11u1 amd64
```

**Comment by masterblaster79** [comment]
Thanks.
One more thing: I had to downgrade liguibase to 4.11:
/var/lib/tomcat9/webapps/jpsonic/WEB-INF/lib/liquibase-core-4.11.0.jar
Otherwise we are hit by this bug and it cannot inset the avatars:
https://github.com/liquibase/liquibase/issues/3165

You want me to open a separate issue for this or can we handle this here as well?

**Comment by masterblaster79** [comment]
Sorry, there is another piece I forgot to mention:
liquibase/jp110.2.0/delete_admin-update_role.xml is missing the ${userTableQuote}

<code>
select count(*) from ${userTableQuote}user${userTableQuote} where username ='admin'
</code>

**Comment by tesshucom** [comment]
Thank you. If you notice any issues, feel free to add them at any time. Let's fix it all.

**Comment by tesshucom** [comment]
#### Progress

 - userTableQuote -> **It will be fixed**
 - SQL exception at the time of data registration -> **It will be fixed**
 - Liguibase 4.11  -> Watch the situation for a few days.
   - The latest 4.17.2 is currently used in Jpsonic's `develop` branch.
   - The patch pointed out has already been merged in Liguibase's master branch. It will be released in 4.18.0.
   - Liguibase 4.18.0 is now "3 days late" in milestone. Therefore, it is better to wait for the next release patch.
     - [Liguibase  4.18.0](https://github.com/liquibase/liquibase/milestone/33?closed=1). See `#3381`.
     - [Maven Central](https://mvnrepository.com/artifact/org.liquibase/liquibase-core)
     - Until next version is released, check various things.

#### Verification now

For the few days, verification will be performed using the [Provisional modified version](https://github.com/tesshucom/jpsonic/actions/runs/3614260594). Now I have used PostgreSQL 15.1, but I plan to check it in some databases. If something is found...it will be fixed.

It's not critical, but for Postgres the internal diagnostics page probably won't work. This needs to be fixed separately.

 - #1813


#### Remarks

For a long time, postgres has been raised on the Blob spec.

 - airsonic/airsonic/pull/1452

As mentioned there, I do not intend to use oid. I think bytea is reasonable.

**Comment by masterblaster79** [comment]
I did a quick check with your verification binaries and it's fine now (with liquibase 4.11 only of course).
Good job.

**Comment by tesshucom** [comment]
Thank you. I also think that there is no problem in operation with 4.11. In the meantime, it looks like 4.18.0 has been released. (#1948) It looks like things are going in the right direction.
A Jpsonic patch release will be coming soon.

**Comment by tesshucom** [comment]
v111.5.11 has been released. Patch version releases are simplified and [**available here**](https://github.com/tesshucom/jpsonic/actions/runs/3644533253) instead of on the releases page.

This issue will be closed. If you have any problems, please feel free to issue a new issue.
