### ISSUE TITLE
HTML problem in the "Don't show again" button for the first start guide.

### ISSUE THREAD

**Issue by DutchComputerKid** [tesshucom/jpsonic#1985]
## Problem description

When setting up the server or using the admin account, the "Don't show again" button for dismissing the first-start guide as seen below:
![image](https://user-images.githubusercontent.com/26170122/210844247-19794284-9fec-4024-a080-adbddb68971a.png)

This can be removed by disallowing the admin user of admin rights and othere shanigans but that would not really be a good idea.

### Steps to reproduce

1. *Set up a new server/instance/session*
2. *The button will/should be there, has been all the time for me.*

## System information

 * **Jpsonic version**: *  Jpsonic 111.5.13 – 2022-12-25*
 * **Operating system**: *Debian 11.6
 * **Java version**: *openjdk 17.0.4 2022-07-19*
 * **Proxy server**: None
 * **Client**: *Firefox, Edge, Chrome*
 * **Language**: *English (United States)*
 * **Tomcat/standalone**: *Docker latest*

**Comment by DutchComputerKid** [comment]
Forgot to mention, this bug makes the admin user completely unable to view the library, how weird as that is.

Also, is there any way to donate to/support you? I'm not the only one with that question. :P

**Comment by tesshucom** [comment]
@DutchComputerKid

As for the Welcome page, there are fixes that have been fixed and will be included in the next release. (The development version is already available.)

 - #1896

If this fix is what you expect, I'll close this issue.

**Comment by DutchComputerKid** [comment]
Updated my docker to the developer version as pointed out here, and yes that fixes it!

Admin can now browse the libraries, and any users with administrative rights can also browse and scan the library without the getting started message blocking everything. Thanks!

**Comment by tesshucom** [comment]
Thank you for confirmation. This issue will be closed.

It included relatively traditional glitches that had been put on the back burner since the Airsonic days, as they had little to do with the internal process. That said, I think this is a relatively unfriendly bug... 

With many bug fixes already accumulating, we may reconsider the fixes planned, for the next release and reconsider our version upgrade plans.
