### ISSUE TITLE
multi genres (4/5) Delete unnecessary index doc before the genre master update

### ISSUE THREAD

**Issue by data-struct** [tesshucom/jpsonic#242]
Lucene index of legacy server is append / update type.
 it is not linked to deletion of DB records.
Consistency of searching from Lucene to DB is guaranteed by "get if not null" .

To ensure consistency, delete doc from Index when deleting DB records .

The goal is not to speed up a single SELECT.
 - It is to be able to count multi genre  in Lucene accurately. (Lucene index has no deletion flag.)
 - As a by-product, it becomes possible to avoid the infinite increase of Lucene index.

#246, #241 

It is possible to merge into the main stream by completing the work so far.
It is possible to apply multi genre related correction while maintaining the legacy function.
___

##### The extension point is below

 - artistDao.expunge();
 - albumDao.expunge();
 - mediaFileDao.expunge();

##### Modification method

Because there is a dependency order, it is not possible to add index operation directly to the postprocessing of dao.

 - Add a method to return the expunge target at Dao.
 - Before calling Dao's expunge, get the expunge target.
 - After Dao's expunge, delete Doc from index using the list of expunge objects obtained in advance

 - This process should be done automatically just before the gen master update, after the end of the scan.
In addition to this, when deleting an index, index-specific processing such as file locking and searcher refresh must be added.

**Comment by tesshucom** [comment]
This change is not made due to the requirement change of #250.

Instead, #242 takes precedence over #252.

**Comment by tesshucom** [comment]
- Create a test case considering "folder addition/deletion/move" and  "scan/dbclean up".
 - Ask for confirmation manually after creating a case for now.
 - If possible, please automate (If there is no problem with manual confirmation, it can be another task).

**Comment by tesshucom** [comment]
### Contents of confirmation

#### delete

Prepare the following data.

ALBUM | FILE | GENRE
-- | -- | --
ALBUM1 | FILE01 | GENRE_A
  | FILE02 | GENRE_A
ALBUM2 | FILE03 | GENRE_B
  | FILE04 | GENRE_C
ALBUM3 | FILE05 | GENRE_D
ALBUM4 | FILE06 | GENRE_D
ALBUM5 | FILE07 | GENRE_E;GENRE_F
  | FILE08 | GENRE_E;GENRE_F
ALBUM6 | FILE09 | GENRE_G;GENRE_H
  | FILE10 | GENRE_I;GENRE_J
ALBUM7 | FILE11 | GENRE_K;GENRE_L
ALBUM8 | FILE12 | GENRE_K;GENRE_L


If counted correctly, the count of genre is as follows.

GENRE | ALBUM count | SONG count
-- | -- | --
GENRE_A | 1 | 2
GENRE_B | 1 | 1
GENRE_C | 0 | 1
GENRE_D | 2 | 2
GENRE_E | 1 | 2
GENRE_F | 1 | 2
GENRE_G | 1 | 1
GENRE_H | 1 | 1
GENRE_I | 0 | 1
GENRE_J | 0 | 1
GENRE_K | 2 | 2
GENRE_L | 2 | 2

 - Delete files 1 to 8 sequentially on the file system.
 - When deleting 2 restore 1 (in the state of deleting only one album in order).　
Run scan at this time.
 - After deleting 8, restore 8 at the end (return to the initial state).
 - During this round of flow, we will check if the genre that can be obtained from the master is as expected.

[genre-delete-test.pdf](https://github.com/tesshucom/jpsonic/files/3204843/genre-delete-test.pdf)

Note that count 0 and "genre not displayed" states have different meanings.

#### move

This verification takes into account the airsonic 1046.

 - Move the Music Folder used for confirmation in delete to a place where the top directory path is different.
 - Clean up the database
 - Create another Music Folder using the moved directory.
 - Run a scan.
 - Check if counting is done with the assumed genre pattern.


![image](https://user-images.githubusercontent.com/27724847/58136759-43f4b900-7c6a-11e9-9c2a-45a1fd87e29a.png)

![image](https://user-images.githubusercontent.com/27724847/58136779-57a01f80-7c6a-11e9-9601-e030355ff4fb.png)

![image](https://user-images.githubusercontent.com/27724847/58136811-71d9fd80-7c6a-11e9-8441-08c2fd4fefd3.png)

(The problems reported in 1046 do not occur. Correct counting is possible.)
