### ISSUE TITLE
multi genres (3/5) Update Genre Master

### ISSUE THREAD

**Issue by tesshucom** [tesshucom/jpsonic#250]
Currently, genres are counted cumulatively at the time of scanning and updated at the end.
Genre master has characteristics as mere count cash mechanism.

Current genre Master can be deleted on design, but needs the count cash mechanism somewhere If deleted.

### Change how to update Genre Master

After scanning, lucene data registered will be counted, and it will be changed to the way to update to the existing genre master.

#### Effects

The change of this method has the following effects.

 - Since lucene index of legacy server is append/update type, it is not linked to deletion of DB records.
This can ensure consistency of count by dealing with deletion.This correction will be handled in #242 .
 - The method of counting lucene registration data after scanning is very suitable for multi genres. This is because Tokenize and parsing are to be able to designed in one place.
 - It is not a big problem though, the order of the getGenres return value list may change. The reason is because only one order is specified in current SQL, legacy SQL depends on the implicit record creation order.

___
#246

phase | Image figure| State
-- | -- | --
phase3 | [genre3.pdf](https://github.com/tesshucom/jpsonic/files/3100652/genre3.pdf) | Fusion with lucene
phase4 | [genre4.pdf](https://github.com/tesshucom/jpsonic/files/3101011/genre4.pdf) | lucene transition of the genre master

**Comment by tesshucom** [comment]
Genre Master can be deleted, but needs to act as a cache somewhere.
So change the requirements.

### Change how to update Genre Master

Currently, genres are counted at the time of scanning and updated at the end.
The reason is to only count valid data.
↓
After scanning, lucene registration data will be counted, and it will be changed to the way to update to the existing genre master.

#### Effects

The change of this method has the following effects.

 - Since lucene index of legacy server is append / update type, it is not linked to deletion of DB records.
This can ensure consistency by dealing with deletion.This correction will be handled in #242 .
 - The method of counting lucene registration data after scanning is very suitable for multi genres. This is because Tokenize and parsing are to be able to designed in one place.

**Comment by jp-searching** [comment]
Specification change of  genre tokenize/filter.
Because the field value of Doc is also conscious of display.

![image](https://user-images.githubusercontent.com/47806044/56837760-7b17ba80-68b6-11e9-96cf-ffa6f7d2b893.png)
![image](https://user-images.githubusercontent.com/47806044/56837773-8cf95d80-68b6-11e9-8358-aac1ee2c1983.png)

**Comment by tesshucom** [comment]
- Delete before update
 - Enable select using multi genre from the screen
 - Update refactoring

**Comment by tesshucom** [comment]
With the above modifications, multi-genre search is possible. It is almost correct, but it needs the following corrections:

- To be Added escape. Gene string needs proper escape handling.
- Create a transfer class, the function related to Index generation of SearchService should be moved to that class. The class dependency is not correct now.

**Comment by tesshucom** [comment]
Description of ehcache.xml :
```
<cache name="mediaFileMemoryCache"
           maxElementsInMemory="1000"
           eternal="false"
           timeToIdleSeconds="0"
           timeToLiveSeconds="10"
           overflowToDisk="false"
           statistics="true"/>
```

```
    <cache name="userCache"
           maxElementsInMemory="1000"
           eternal="false"
           timeToIdleSeconds="172800"
           timeToLiveSeconds="172800"
           overflowToDisk="false"
           diskSpoolBufferSizeMB="1"
           statistics="true"/>
```
___

#### MediaFileService#mediaFileMemoryCache
It does not specify in the package, but has its own cache instance.
(The cache is off when during updating scan.)

There is no effect as the path of change does not include this cache.
