### ISSUE TITLE
 Search Index downsizing

### ISSUE THREAD

**Issue by tesshucom** [tesshucom/jpsonic#253]
- Create a new filter and reduce the index size without reducing the accuracy.
Will be addressed before #249.
 - Test case correction
 - Index version upgrade

<table>
	<tbody>
		<tr>
			<th>Contents of change</th>
			<th>Field name</th>
			<th>Registration rule</th>
		</tr>
		<tr>
			<td>delete</td>
			<td>ALBUM_FULL</td>
			<td>Other than Hiragana</td>
		</tr>
		<tr>
			<td>delete</td>
			<td>ALBUM_READING_HIRAGANA</td>
			<td>Only hiragana</td>
		</tr>
		<tr>
			<td>delete</td>
			<td>TITLE_READING_HIRAGANA</td>
			<td>Only hiragana</td>
		</tr>
		<tr>
			<td>add</td>
			<td>ARTIST_EX</td>
			<td>When it consists only stop-word.</td>
		</tr>
		<tr>
			<td>add</td>
			<td>ALBUM_EX</td>
			<td rowspan="2">When it consists only of hiragana or stop-word.</td>
		</tr>
		<tr>
			<td>add</td>
			<td>TITLE_EX</td>
		</tr>
	</tbody>
</table>

EX field is a field for easily dealing with rare cases difficult for analysis.
(`La, La, La` etc)
 - Keep the size as small as possible, but there should be no unsearchable words.
 - Japanese Tokenizer is difficult to customize by inheritance. 
Therefore, a complementary field is provided.

Ignoring minor speed issues makes it easier to test as it is visualized (with luke or debugger).

Before and after the change, measure the following.

 - Number of songs in test environment, data breakdown.
 - DB file size.
 - Index file size.

**Comment by tesshucom** [comment]
## tokenize / fileter specification

![image](https://user-images.githubusercontent.com/27724847/56476770-00c2f100-64d8-11e9-9323-8a82454f38b5.png)

![image](https://user-images.githubusercontent.com/27724847/56476786-31a32600-64d8-11e9-8d21-a877f8920776.png)

**Comment by jp-searching** [comment]
artist 118
album 342
song 3,855
__
(on disk)
#### after
DB      4,505,600
Index     827,392
#### before
DB      4,509,696
Index     847,872
__
The size is almost the same, but this is fine as the content is more accurate.
Deduplication between fields can reduce the size,
but further updates require additional database test cases.
