### ISSUE TITLE
 Mystery of genre update

### ISSUE THREAD

**Issue by tesshucom** [tesshucom/jpsonic#272]
(reported by Airsonic) 

Cases where scanning after data copy can not be performed correctly.
I do not know well whether it is the intended specification or a defect.

 - Gene update case under the same name atist / album in different Musicfolder, or similar situation
 - If my memory is correct, this problem may also affect UPnP and Sonos.

However, because the repeatability has not been determined, the progress is being watched.
___

##### LastScanned may not be determined correctly ... ?

The determination performed in L316 is premised on that the candidate album has been correctly searched at L294.

https://github.com/airsonic/airsonic/blob/2c3ba680d8100e140d4b9abd439145baea14fb74/airsonic-main/src/main/java/org/airsonic/player/service/MediaScannerService.java#L288-L342

##### Search for lastScanned match target ... ?

It seems that path comparison is needed to correctly determine the case raised in this issue.

https://github.com/airsonic/airsonic/blob/2c3ba680d8100e140d4b9abd439145baea14fb74/airsonic-main/src/main/java/org/airsonic/player/dao/AlbumDao.java#L61-L91

But the album name & artist name match and the file is "existing" .
Judgment of the corresponding part is id3, but the problem is derived from the file structure side.

**Comment by jp-searching** [comment]
Conduct the test conducted on #242 on Airsonic.
