### ISSUE TITLE
Update Spring Boot

### ISSUE THREAD

**Issue by cve-hotfix** [tesshucom/jpsonic#275]
Update Spring Boot Web Starter to 1.5.21.RELEASE.
Investigation of overriding dependencies.

 - jetty
 - tomcat
 - ~~jaxb~~ 　ecj
[jpsonic-101.2.0(before).pdf](https://github.com/tesshucom/jpsonic/files/3225049/jpsonic-101.2.0.before.pdf)

**Comment by tesshucom** [comment]
[jpsonic-101.3.0(after).pdf](https://github.com/tesshucom/jpsonic/files/3225131/jpsonic-101.3.0.after.pdf)

 - Removed jetty and tomcat overrides.
 - Keep overriding ecj (Spring's ecj is 3.12.3, so you can not compile the jetty profile without overriding it.)
