### ISSUE TITLE
Merge Airsonic 10.3.1 -> 10.4.0-SNAPSHOT

### ISSUE THREAD

**Issue by tesshucom** [tesshucom/jpsonic#278]
Follow the steps below to merge.

 - [x] 102.0.0

 - Merge 10.3.1-RELEASE to 101.1.0 and create 102.0.0-snapshot
 - Merge 101.2.0-snapshot, which was being developed for the next release, against 102.0.0-snapshot (multi-genre).
 - Release 102.0.0

❗️
Jetty CVE suppression will be excluded. Jpsonic does jetty support.

 - [x] 103.0.0
 - Merge 10.4.0 SNAPSHOT to 102.0.0

**Comment by tesshucom** [comment]
1075 is blocking (LFS storage broken).
SNAPSHOT can not be obtained.

**Comment by file-struct** [comment]
1075 finished, but merge / checkout is not possible for instances created before gitlab.
Something needs to be done.

**Comment by file-struct** [comment]
```
git lfs install --skip-smudge --local
git remote add airsonic https://github.com/airsonic/airsonic.git
git fetch airsonic
git merge airsonic
git commit
git pull
git lfs pull https://github.com/airsonic/airsonic.git
git lfs install --force --local
git push
```
