### ISSUE TITLE
Update to Lucene 8.2.0

### ISSUE THREAD

**Issue by tesshucom** [tesshucom/jpsonic#284]
The content corresponds to the Airsonic PR of the same name.
Airsonic's review will take time.
Therefore, merge the contents of PR ahead.

In order to make a large migration from PR 3.x to 8.x, very redundant comments are described.
Merge this as it is.

**Comment by jp-searching** [comment]
The Genre count correction made in # 250 cannot be reproduced in 8.x.

There was probably a fix for writing the index between 7.x and 8.x, and the syncing process now takes longer.
It can be avoided by adding logic to wait for Thread to write the file, but the genre master update cost is higher than before.

The logic to perform genre counting during a scan as before is cumbersome, but now it is a better choice.
