### ISSUE TITLE
Improve sorting

### ISSUE THREAD

**Issue by tesshucom** [tesshucom/jpsonic#301]
There are several sort algorithms in the server.
Due to the difference in the current sort logic, the sort order is slightly different depending on the display location.

Add test data that can be confirmed.

**Comment by jp-sorting** [comment]
Make the following changes.

 - Change PlayQue sort to ignoreCase
 - Changed to be able to handle sequential number sort by setting option

Since it is easy to check ignoreCase, add serial number confirmation data.
