### ISSUE TITLE
Service sorting improvements

### ISSUE THREAD

**Issue by tesshucom** [tesshucom/jpsonic#304]
Some controllers have provisional implementations of sorting.
These don't work correctly.

 - [x] Sharing a part of #302 sort process.
 - [x] Check if it can be avoided by improving Dao.  -> (impossible)
 - [x] Use the data of #302 to Improve outstanding controllers. -> Standardize and test the implementation

**Comment by jp-sorting** [comment]
Sort logic is implemented by many people individually and left for a long time.
Since there are many differences in implementation, standardize and test.

Since there are many corrections, divide roughly into presentation units and make corrections from areas with high demand.

**Comment by tesshucom** [comment]
Exclude some tests.
It will be solved by #306.
