### ISSUE TITLE
RecentAlbum displays differently on Web/DLNA

### ISSUE THREAD

**Issue by tesshucom** [tesshucom/jpsonic#313]
#305

RecentAlbum display may be different between Web and DLNA.

(It's not completely different, it's a little different.)
There's no big difference in the code and I don't know why.

**Comment by tesshucom** [comment]
Even when running with travis, you can (sometimes) reproduce it.

![image](https://user-images.githubusercontent.com/27724847/66716801-03f6c400-ee0d-11e9-897d-5800d25be1be.png)

**Comment by jp-sorting** [comment]
The reason is as follows : 

 - Web uses NewAlbum (MediaFileDao) file structure
 - Rest and DLNA use ID3 NewAlbum (AlbumDao)
 - Sort rule is date desc only. Therefore, if the date is the same, it will be affected (by the insertion order of Database?).

**Comment by tesshucom** [comment]
There is no impact if the dates are different, so there is little impact on usability.
There is no response at this time.
