### ISSUE TITLE
Fix image URL generation logic for DLNA 

### ISSUE THREAD

**Issue by tesshucom** [tesshucom/jpsonic#322]
Id3 image is incorrect.
Modify so that DLNA image processing is performed correctly.

**Comment by jp-sorting** [comment]
The problem occurs with Id3 artists and album images.

 - BubbleUPnP can confirm this phenomenon
 - Does not occur in MediaMonkey

Since there is a high possibility that this is a problem specific to BubbleUPnP, we do not take action at present.

**Comment by tesshucom** [comment]
Probably the Airsonic has degrated.

**Comment by tesshucom** [comment]
Traditional Airsonic bug.
It may correspond later.

**Comment by tesshucom** [comment]
- There is a bug in the DLNA image resource URL generation logic.
 - Image resource URL generation rules are the same as Subsonic (That is, they were merged before Libresonic's Fork).  The scope of the bug is limited to the scope of DLNA implementation.
 - MediaMonkey (for PC) can display images correctly even in a malfunction state. It's just a coincidence. There may also be problems with the implementation of MediaMonkey (for PC).
 - MediaMonkey (for Android) and BubbleUPnP (for Android) cannot handle image resources correctly in a faulty state.
 - If a bug is fixed, MediaMonkey (for Android) and BubbleUPnP (for Android) will always display correctly. On the other hand, with MediaMonkey (for PC), Id3 images cannot be displayed.

Fix the image URL generation logic correctly.

**Comment by tesshucom** [comment]
I confirmed that BubbleUPnP can display Artist (file / id3) / Album (file / id3) / Song / Playlist images.
