### ISSUE TITLE
English we want to read in Japanese

### ISSUE THREAD

**Issue by tesshucom** [tesshucom/jpsonic#324]
Sort tags have a major impact on index generation.
It should be improve index, sort, and search behavior when Japanese readings are registered against English.

 - Even if Japanese readings are registered for English in sort-tag, create an index that separates English and Japanese (or switch as an option).
 - Use sort-tag and name when searching (maintain the current status).

Japanese voice assistance has not decided whether to return Japanese or English for English input.
To be able to handle both.

**Comment by tesshucom** [comment]
#323
Add an icon to add an option.

**Comment by data-struct** [comment]
Need full scan option to switch.
