### ISSUE TITLE
Add a forced full scan

### ISSUE THREAD

**Issue by data-struct** [tesshucom/jpsonic#330]
Although it is not used frequently, forced full scan is required to construct some data such as regenerating sort keys (#324).
Optionally add an option to perform a full scan.

**Comment by tesshucom** [comment]
Statics implementation has changed, should be done after #334.

**Comment by tesshucom** [comment]
A full scan takes a considerable amount of time.
Reject at the moment.

The correspondence is changed as follows.

 - Move the option added in #324 to the scan page
 - Set to disable on the screen side to prevent switching(Keep internal implementation)
