### ISSUE TITLE
Cleanup during scanning

### ISSUE THREAD

**Issue by jp-searching** [tesshucom/jpsonic#397]
Shouldn't do any cleanup during the scan, but the legacy probably didn't consider.
Since the addition of Lucene is added to the cleanup, the exclusive design needs to be reviewed.
If this operation is performed, the index cannot be written.

It is not serious because it will return if you restart.
However, since the user cannot visually judge, a phenomenon that occurs after falling into an inappropriate lock state may be reported as a secondary failure.
If it can be reproduced on the airsonic side, the airsonic side also needs to be modified.

**Comment by tesshucom** [comment]
https://github.com/airsonic/airsonic/pull/1550/commits/7dc4d5ac7ad3ecc5bacd092ec225607a643a7f5e

Sent to Airsonic.

**Comment by tesshucom** [comment]
Airsonic PR updated, merged.
Fix to prevent cleanup during scan to maintain data consistency.
