### ISSUE TITLE
Only the query of the specific pattern is skipped in UPnP search

### ISSUE THREAD

**Issue by tesshucom** [tesshucom/jpsonic#409]
When is searched for the title of the song class, artist is also included in the condition.
Or add ``that option``.

**Comment by tesshucom** [comment]
(In the case of BubbleUPnP) Possibility of ignoring artists in certain container classes...?

A little research is needed.
If there is a good way, adopt that policy.

All-or-nothing has practical problems, so if there is no good way, interpret the input as an option separately.
(Airsonic seems to have implemented its own)

**Comment by data-struct** [comment]
There is a defect in the following conditions : 
(derivedfrom "object.item.audioItem" and (dc:creator contains  ??? or upnp:artist contains ??? ))

 - In UPnPCriteriaDirectorTestCase#testSearchQuery5, unit tests for analysis are working properly
 - There is a problem with the integration. In DispatchingContentDirectory#search, If enter a query that the case, the process is strangely skipped.

**Comment by jp-searching** [comment]
There is a defect in the following conditions : 
``(derivedfrom "object.item.audioItem" and (dc:creator contains  ??? or upnp:artist contains ??? ))``

 - In UPnPCriteriaDirectorTestCase#testSearchQuery5, unit tests for analysis are working properly
 - There is a problem with the integration. In DispatchingContentDirectory#search, If enter a query that the case, the process is strangely skipped.

**Comment by jp-searching** [comment]
BrowseResult#search is bubbling the exception.
It didn't return error notifications to the log, so it seemed strangely skipped.
