### ISSUE TITLE
Change ID3 album scan specifications

### ISSUE THREAD

**Issue by tesshucom** [tesshucom/jpsonic#414]
The Sonic server summarizes the album as it scans.
However, there is no test case.
Add test cases to prevent degrate.

**Comment by data-struct** [comment]
This is a legacy impl bug.

FileStructure albums are created based on first child.
Id3 overwrites recursively, so if an album with the same name already exists, many properties will be overwritten.
This can result in combinations of property sets that should not exist.
Only the relevant case was modified and changed to refer to the same first child as FileStructure.
Other cases are fine.
