### ISSUE TITLE
Modify UPnP container type

### ISSUE THREAD

**Issue by tesshucom** [tesshucom/jpsonic#415]
- Genre
 - First level of Index
 - First level of FileStructure(Artist)

#### Artist

Probably it will not be possible to display Artist cover art via WEB in the future.

~~It is not appropriate that the container type is Artist.~~
It should be to not display images for artist of file structure.
If Airsonic has implemented the image editing function, correct it again.

**Comment by view-ext** [comment]
Changed as follows : 

Processor | changed item | Before | After
-- | -- | -- | --
AlbumByGenre | Genre | object.container.album.musicAlbum | object.container.genre
IndexId3 | Artist | object.container.album.musicAlbum | object.container.person.musicArtist
IndexId3 | Index | object.container.album.musicAlbum | object.container.genre
Index | Artist | object.container.album.musicAlbum | object.container.person.musicArtist
Index | Index | object.container.album.musicAlbum | object.container.genre
MediaFile | Artist | object.container.album.musicAlbum | object.container.person.musicArtist

**Comment by view-ext** [comment]
Changed as follows : 

Processor | Changed item | Before | After
-- | -- | -- | --
AlbumByGenre | Genre | object.container.album.musicAlbum | object.container.genre
IndexId3 | Artist | object.container.album.musicAlbum | object.container.person.musicArtist
IndexId3 | Index | object.container.album.musicAlbum | object.container.genre
Index | Artist | object.container.album.musicAlbum | object.container.person.musicArtist
Index | Index | object.container.album.musicAlbum | object.container.genre
MediaFile | Artist | object.container.album.musicAlbum | object.container.person.musicArtist
MediaFile | MusicFolder | object.container.album.musicAlbum | object.container.storageFolder
