### ISSUE TITLE
Organize history

### ISSUE THREAD

**Issue by tesshucom** [tesshucom/jpsonic#418]
There is a history that is skipped for several reasons.

 - Temporarily simplified and merged because Airsonic Master is not a single line
 - Skipped commits related to LFS (Integration test)

Rearrange this and recreate a branch that does not conflict with Airsonic.

If a major version of Airsonic is released, merge that branch and increment the major version of Jpsonic.

**Comment by file-struct** [comment]
Re-merge based on 80ccd82 because we squashed some commits.
The result is an empty commit.

The code has been adjusted to Airsonic only for AudioTagger.
No change in processing.
