### ISSUE TITLE
Migrate query generation to builder pattern

### ISSUE THREAD

**Issue by tesshucom** [tesshucom/jpsonic#423]
Increased requirements make testing difficult with current designs.
Migrate existing search to builder pattern, similar to UPnP search.

Create and test a builder that can generate a variety of queries when you change conditions.
The existing SearchImpl only searches.
Initially, we only change the class structure and organize the tests.
Later, we will add a new condition to the builder.

**Comment by tesshucom** [comment]
Rebase #424. 

The case of the album in IndexManagerTestCase.java has been changed, but the original was incorrect.

**Comment by tesshucom** [comment]
The method of construct for Director, and Criteria have been officially redefined.
A decision table for query generation can be created.
Clean up some existing tests.

**Comment by jp-searching** [comment]
Reorganize existing tests.
It is not exhaustive all, but sufficient for confirming important parts.
